# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "is-git-url-1.0.0" = {
      name = "is-git-url";
      packageName = "is-git-url";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-git-url/-/is-git-url-1.0.0.tgz";
        sha1 = "53f684cd143285b52c3244b4e6f28253527af66b";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "semver-7.3.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.4.tgz";
        sha512 = "tCfb2WLjqFAtXn4KEdxIhalnRtoKFN7nAwj0B3ZXCbQloV2tq5eDbcTmT68JJD3nRJq24/XgxtQKFIpQdtvmVw==";
      };
    };
    "simple-git-1.132.0" = {
      name = "simple-git";
      packageName = "simple-git";
      version = "1.132.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-git/-/simple-git-1.132.0.tgz";
        sha512 = "xauHm1YqCTom1sC9eOjfq3/9RKiUA9iPnxBbrY2DdL8l4ADMu0jjM5l5lphQP5YWNqAL2aXC/OeuQ76vHtW5fg==";
      };
    };
    "upath-1.2.0" = {
      name = "upath";
      packageName = "upath";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/upath/-/upath-1.2.0.tgz";
        sha512 = "aZwGpamFO61g3OlfT7OQCHqhGnW43ieH9WZeP7QxN/G/jS4jfqUkZxoryvJgVPEcrl5NL/ggHsSmLMHuH64Lhg==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
in
{
  "elm-git-install-git://github.com/robinheghan/elm-git-install" = nodeEnv.buildNodePackage {
    name = "elm-git-install";
    packageName = "elm-git-install";
    version = "0.1.3";
    src = fetchgit {
      url = "git://github.com/robinheghan/elm-git-install";
      rev = "b2cafc99ac6eeb3d7eda97cb3246ba033b21825a";
      sha256 = "65f37ca53f783da67ed6e8b2c44229ccceae3a9d8159f555188048c14bb93343";
    };
    dependencies = [
      sources."debug-4.3.2"
      sources."is-git-url-1.0.0"
      sources."lru-cache-6.0.0"
      sources."ms-2.1.2"
      sources."semver-7.3.4"
      sources."simple-git-1.132.0"
      sources."upath-1.2.0"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A tool for installing private Elm packages from any git url.";
      homepage = "https://github.com/Skinney/elm-git-install#readme";
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}